#!/bin/bash

#./run_clients_local [abs_path_to_hosts_file] [nbr_of_clients] [reqs_per_client]
# NOTE that nbr_of_clients should be a multiple of the number of nodes
# /Users/axelniklasson/dev/practicalbft/BFTList/conf/hosts.txt
 
 if [ "$#" -ne 3 ]; then
    echo "Run as ./run_clients_local [abs_path_to_hosts_file] [nbr_of_clients] [reqs_per_client]"
    exit 1
fi

NODES=$(cat ${1} | wc -l)
echo "Sending requests to nodes"
for i in $(seq 0 $(($NODES-1))); do
    HOSTS_PATH=$1 python client.py $i $2 $3 &> /dev/null &
done
echo "Done!"